name: Generate Google Merchant feed

'on':
  workflow_dispatch:
  schedule:
    - cron: "17 4 * * *"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm workflow works
        run: echo "Workflow veikia"
